---
- name: Install node and npm
  hosts: 65.1.3.136 
  tasks:
    # - name: Update apt repo and cache
    #   yum: update_cache=yes force_yum_get=yes cache_valid=3600
    - name: Install nodejs and npm
      yum:
        name:
          - nodejs
          - npm
        state: latest
        # update_cache: true

- name: Deploy nodejs app
  hosts: 65.1.3.136 
  tasks:
    # - name: Copy nodejs folder to a server
    #   copy:
    #     src: /Users/jason/Demo-projects/Bootcamp
    #     dest: /root/app-1.0.0.tgz 
    - name: Unpack the nodejs file
      unarchive: 
        src: /Users/jason/Demo-projects/Bootcamp
        dest: /root/
        # remotesrc: yes
