---
- name: Install node and npm
  hosts: 13.233.63.48
  become: true
  tasks:
  - name: Update package index
    yum:
      update_cache: true
  - name: Add Node.js package repository
    shell: curl -sL https://rpm.nodesource.com/setup_12.x | bash -
  - name: Install Node.js
    yum:
      name: nodejs
      state: present

- name: Create new Linux user for node app
  hosts: 13.233.63.48
  become: True
  tasks:
    - name: Create linux user
      user:
        name: jason
        comment: jason adm
        group: admin

- name: Deploy nodejs app
  hosts: 13.233.63.48
  become: True
  become_user: jason 
  tasks:
  - name: copy
    copy: 
      src: /home/jason/Documents/practice/boto3/main.py
      dest: /home/jason/main.py
  - name: Install dependencies
    npm:
      path: /home/jason/package
  - name: Start the app
    command:
      chdir: /home/jason
      cmd: node --version
    async: 1000
    poll: 0
  - name: Ensure app is running
    shell: ps aux | grep node
    register: app_status
  - debug: msg={{app_status}} 

